### PR TITLE
fix: ReferenceError window is not defined

### LINKED ISSUE #19: WebpackError: ReferenceError: window is not defined
When I try to build my gatsby application this error occurs and it breaks my build.
I think this can be resolved moving window.addEventListener to componentDidMount.

### PR DESCRIPTION
**Pull request by mathvaleriano**
Hi, 
I made this PR because I need to do my build in gatsby... 
I hope it's ok to merge.
So the main changes are:

- change to PureComponent to improve performance
- move state outside of constructor and set a initial value
- move listener to componentDidMount to use on SSR
- add removeListener when component will unmount

It'll resolve #19

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -1,21 +1,32 @@
...
+export default class StepWizard extends PureComponent {
+    state = {
+        activeStep: 0,
+        classes: {},
+        hashKeys: {},
+    }
 
-        this.state = this.initialState();
+    componentDidMount() {
+        this.setState({ ...this.initialState() });
```
Comment (jcmcneal) [inline src/index.js]: Most of this looks great, but my concern is calling `setState` inside `componentDidMount` since it will render twice on load. What are your thoughts?

Comment (mathvaleriano) [reply src/index.js]: It doesn't render twice on load. It's not a  anti-pattern because you can call setState when you use some async operations like fetch some values of api (https://reactjs.org/docs/faq-ajax.html).
If component calls this lifecycle again then it should destroy all values and remove subscribers. I think if it is passed into a shouldComponentUpdate or componentDidUpdate should generate errors like what you said.

Comment (jcmcneal) [reply src/index.js]: This is in the React [documentation](https://reactjs.org/docs/react-component.html#componentdidmount):
`You may call setState() immediately in componentDidMount(). It will trigger an extra rendering, but it will happen before the browser updates the screen.`

It's definitely not an anti-pattern but I wanted to consider any potential performance issues. We don't know what kind of components with lifecycles people will use as steps so if they are using `componentDidMount` too the initial state won't be set in the first, unnoticeable, render.

If you don't think this should be an issue I'll go ahead and merge.

Comment (mathvaleriano) [reply src/index.js]: I'll try to change it. Thank you for the explanation :smile:

**Comment by mathvaleriano** [comment]
I made the rowback of setState to put into the constructor again :smile:

**Comment by jcmcneal** [comment]
Cool, does the `getHash` method not error out on SSR? Also, can I have you merge into the `dev` branch, please? That way I can do some local testing on it before going to master.

**Comment by mathvaleriano** [comment]
sounds great for me. and yes gethash makes an error... sorry about that

**Comment by mathvaleriano** [comment]
> Cool, does the `getHash` method not error out on SSR? Also, can I have you merge into the `dev` branch, please? That way I can do some local testing on it before going to master.

 I can't think for now in how to change that, and you?

**Comment by jcmcneal** [comment]
What if after the state declaration in `initialState` we do
```js
if (typeof window === undefined) return state;
```

Any issues with that?

**Comment by mathvaleriano** [comment]
> What if after the state declaration in `initialState` we do
> 
> ```js
> if (typeof window === undefined) return state;
> ```
> 
> Any issues with that?

I think so. Because it'll not activate the initial tab by hash unless the window listener automatically calls onHashChange when it enters in componentDidMount.

**Comment by jcmcneal** [comment]
I need to spin up an instance of Gatsby so I can test it out but I believe the constructor will execute on both the server and client side, is that correct?

**Comment by mathvaleriano** [comment]
Yes it will.

**Comment by jcmcneal** [comment]
Let me know when you have a final change and I'll merge and test.

**Comment by mathvaleriano** [comment]
> Let me know when you have a final change and I'll merge and test.

I've used your suggestion and it works :smile: I'll send the code

**Comment by mathvaleriano** [comment]
Done. Could you test it, please?
