### PR TITLE
Bug fixes

### LINKED ISSUE #12: Crash when single child present
The following error occurs when there is only a single child passed to `StepWizard`:

> Uncaught TypeError: o.props.children.forEach is not a function

You may want to consider guarding against this at least for developer sanity :)

### PR DESCRIPTION
**Pull request by jcmcneal**
#12 
#13 
#17

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -132,6 +133,9 @@ export default class StepWizard extends Component {
         window.location.hash = this.state.hashKeys[activeStep];
     }
 
+    // Allows for using HTML elements as a step
+    isReactComponent = type => typeof type === 'function'
```
Comment (jorbascrumps) [inline src/index.js]: Nothing against your fix, just wanted to point out that `Component.prototype.isReactComponent` is provided by React itself. Checkout [this article](https://overreacted.io/how-does-react-tell-a-class-from-a-function/) and [this relevant code](https://github.com/facebook/react/blob/769b1f270e1251d9dbdce0fcbd9e92e502d059b8/packages/react-reconciler/src/ReactFiber.js#L297-L300) from React source.

Comment (jcmcneal) [reply src/index.js]: Oh nice! That seems like it would be a more stable option.
